###########
# site.url, site.title

title: 'Pyriotous'

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
# path: /jekyll-bootstrap-theme
url: "http://www.pyriotous.com"

########
# more settings

markdown: kramdown

sass:
  sass_dir: css
  style:    expanded

include: ['_pages']

collections:
  - shirts
  - vids

collections:
  shirts:
    permalink: /shirts/:path/
    output: true
  vids:
    permalink: /videos/:path/
    output: true

exclude:
- README.md

